version: '3.8'

services:
  db-webdinamis:
    image: mariadb:10.6
    container_name: db-webdinamis
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password!123'
      MYSQL_DATABASE: 'uas33'
      MYSQL_USER: 'Nunu'
      MYSQL_PASSWORD: 'uas123'
    volumes:
      - db_data_volume:/var/lib/mysql
      - ./db_data/uas33.sql:/docker-entrypoint-initdb.d/uas33.sql
    networks:
      - uas_network

  dynamic-web:
    image: ${DOCKERHUB_USERNAME}/uas-dinamis:latest
    container_name: uas-dinamis
    restart: always
    depends_on:
      - db-webdinamis
    ports:
      - "3000:3000"
    environment:
      APP_ENV: production
      APP_DEBUG: 'true'
      APP_KEY: 'base64:a9Fgo08SdmnHq7cAbeLYI65VVA/vIvfgFgN6+gAMNME='
      DB_CONNECTION: mysql
      DB_HOST: db-webdinamis
      DB_PORT: 3306
      DB_DATABASE: uas33
      DB_USERNAME: Nunu
      DB_PASSWORD: uas123
      APP_URL: http://${AWS_HOST:-localhost}
    networks:
      - uas_network

  static-web:
    image: ${DOCKERHUB_USERNAME}/uas-statis:latest
    container_name: uas-statis
    restart: always
    depends_on:
      - dynamic-web
    ports:
      - "80:80"
    networks:
      - uas_network

volumes:
  db_data_volume:

networks:
  uas_network:
